# Generated by Django 2.0.7 on 2018-07-12 15:25

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_ormlogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='profiles'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
