# Generated by Django 2.0.1 on 2018-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormexperience',
            name='saves_count',
            field=models.IntegerField(default=0),
        ),
    ]
