# Generated by Django 2.0.1 on 2018-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_ormexperience_saves_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormexperience',
            name='share_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
