# Generated by Django 2.0.7 on 2018-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_auto_20180703_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormexperience',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
