# Generated by Django 2.0.7 on 2018-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_title_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormexperience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
