# Generated by Django 2.0.7 on 2018-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormscene',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
