# Generated by Django 2.0.7 on 2018-07-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_ormlogintoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormperson',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='ormperson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ormperson',
            name='username',
        ),
    ]
